/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddToCartDto
 */
export interface AddToCartDto {
    /**
     * ID of the product to add to cart
     * @type {number}
     * @memberof AddToCartDto
     */
    'product_id': number;
    /**
     * Quantity to add (1-99)
     * @type {number}
     * @memberof AddToCartDto
     */
    'quantity': number;
}

