/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthControllerUnlinkOAuthRequest
 */
export interface AuthControllerUnlinkOAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthControllerUnlinkOAuthRequest
     */
    'provider'?: AuthControllerUnlinkOAuthRequestProviderEnum;
}

export const AuthControllerUnlinkOAuthRequestProviderEnum = {
    GOOGLE: 'google',
    FACEBOOK: 'facebook',
    GITHUB: 'github'
} as const;

export type AuthControllerUnlinkOAuthRequestProviderEnum = typeof AuthControllerUnlinkOAuthRequestProviderEnum[keyof typeof AuthControllerUnlinkOAuthRequestProviderEnum];


