/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CategoriesControllerReorderRequestCategoriesInner } from './categories-controller-reorder-request-categories-inner';

/**
 * 
 * @export
 * @interface CategoriesControllerReorderRequest
 */
export interface CategoriesControllerReorderRequest {
    /**
     * 
     * @type {Array<CategoriesControllerReorderRequestCategoriesInner>}
     * @memberof CategoriesControllerReorderRequest
     */
    'categories'?: Array<CategoriesControllerReorderRequestCategoriesInner>;
}

