/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateDiscountDto
 */
export interface CreateDiscountDto {
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    'discount_type': CreateDiscountDtoDiscountTypeEnum;
    /**
     * Percentage (1-100) or amount in VND
     * @type {number}
     * @memberof CreateDiscountDto
     */
    'discount_value': number;
    /**
     * 
     * @type {number}
     * @memberof CreateDiscountDto
     */
    'min_order_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDiscountDto
     */
    'max_discount_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDiscountDto
     */
    'max_uses'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDiscountDto
     */
    'max_uses_per_user': number;
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    'starts_at': string;
    /**
     * 
     * @type {string}
     * @memberof CreateDiscountDto
     */
    'ends_at': string;
}

export const CreateDiscountDtoDiscountTypeEnum = {
    PERCENTAGE: 'percentage',
    FIXED_AMOUNT: 'fixed_amount',
    FREE_SHIPPING: 'free_shipping'
} as const;

export type CreateDiscountDtoDiscountTypeEnum = typeof CreateDiscountDtoDiscountTypeEnum[keyof typeof CreateDiscountDtoDiscountTypeEnum];


