/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateOrderDto
 */
export interface CreateOrderDto {
    /**
     * Shipping address ID (from user addresses)
     * @type {number}
     * @memberof CreateOrderDto
     */
    'shipping_address_id': number;
    /**
     * Billing address ID (optional, defaults to shipping)
     * @type {number}
     * @memberof CreateOrderDto
     */
    'billing_address_id'?: number;
    /**
     * Payment method
     * @type {string}
     * @memberof CreateOrderDto
     */
    'payment_method': CreateOrderDtoPaymentMethodEnum;
    /**
     * Shipping method
     * @type {string}
     * @memberof CreateOrderDto
     */
    'shipping_method': CreateOrderDtoShippingMethodEnum;
    /**
     * Customer phone (override from address if needed)
     * @type {string}
     * @memberof CreateOrderDto
     */
    'customer_phone'?: string;
    /**
     * Discount code (optional)
     * @type {string}
     * @memberof CreateOrderDto
     */
    'discount_code'?: string;
    /**
     * Customer note (optional)
     * @type {string}
     * @memberof CreateOrderDto
     */
    'customer_note'?: string;
}

export const CreateOrderDtoPaymentMethodEnum = {
    COD: 'cod',
    BANK_TRANSFER: 'bank_transfer',
    MOMO: 'momo',
    ZALOPAY: 'zalopay',
    VNPAY: 'vnpay'
} as const;

export type CreateOrderDtoPaymentMethodEnum = typeof CreateOrderDtoPaymentMethodEnum[keyof typeof CreateOrderDtoPaymentMethodEnum];
export const CreateOrderDtoShippingMethodEnum = {
    STANDARD: 'standard',
    EXPRESS: 'express',
    SAME_DAY: 'same_day'
} as const;

export type CreateOrderDtoShippingMethodEnum = typeof CreateOrderDtoShippingMethodEnum[keyof typeof CreateOrderDtoShippingMethodEnum];


