/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateCategoryDto
 */
export interface CreateCategoryDto {
    /**
     * Parent category ID for nested categories (null for root level)
     * @type {number}
     * @memberof CreateCategoryDto
     */
    'parent_id'?: number | null;
    /**
     * Category name
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'name': string;
    /**
     * Category description
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'description'?: string;
    /**
     * Category image URL
     * @type {string}
     * @memberof CreateCategoryDto
     */
    'image_url'?: string;
    /**
     * Display order (lower number = higher priority)
     * @type {number}
     * @memberof CreateCategoryDto
     */
    'display_order'?: number;
    /**
     * Whether category is active
     * @type {boolean}
     * @memberof CreateCategoryDto
     */
    'is_active'?: boolean;
}

