/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
    /**
     * Full name of the user
     * @type {string}
     * @memberof RegisterDto
     */
    'full_name': string;
    /**
     * User email address
     * @type {string}
     * @memberof RegisterDto
     */
    'email': string;
    /**
     * Phone number (10-20 digits) - Optional
     * @type {string}
     * @memberof RegisterDto
     */
    'phone'?: string;
    /**
     * Password (min 8 chars, must contain uppercase, lowercase, number, and special character)
     * @type {string}
     * @memberof RegisterDto
     */
    'password': string;
}

