/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResetPasswordDto
 */
export interface ResetPasswordDto {
    /**
     * Password reset token from email
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'token': string;
    /**
     * New password (min 8 chars, must contain uppercase, lowercase, number, and special character)
     * @type {string}
     * @memberof ResetPasswordDto
     */
    'new_password': string;
}

