/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SearchProductDto
 */
export interface SearchProductDto {
    /**
     * Search keywords
     * @type {string}
     * @memberof SearchProductDto
     */
    'query': string;
    /**
     * Fields to search in
     * @type {Array<string>}
     * @memberof SearchProductDto
     */
    'fields'?: Array<SearchProductDtoFieldsEnum>;
    /**
     * Search mode: exact or fuzzy
     * @type {string}
     * @memberof SearchProductDto
     */
    'mode'?: SearchProductDtoModeEnum;
}

export const SearchProductDtoFieldsEnum = {
    NAME: 'name',
    DESCRIPTION: 'description',
    BRAND: 'brand',
    MODEL: 'model',
    SKU: 'sku'
} as const;

export type SearchProductDtoFieldsEnum = typeof SearchProductDtoFieldsEnum[keyof typeof SearchProductDtoFieldsEnum];
export const SearchProductDtoModeEnum = {
    EXACT: 'exact',
    FUZZY: 'fuzzy'
} as const;

export type SearchProductDtoModeEnum = typeof SearchProductDtoModeEnum[keyof typeof SearchProductDtoModeEnum];


