/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCartItemDto
 */
export interface UpdateCartItemDto {
    /**
     * New quantity (1-99, or 0 to remove)
     * @type {number}
     * @memberof UpdateCartItemDto
     */
    'quantity': number;
}

