/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateAddressDto
 */
export interface UpdateAddressDto {
    /**
     * Recipient name
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'recipient_name'?: string;
    /**
     * Phone number (Vietnamese format)
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'phone'?: string;
    /**
     * Full address line (street, building, etc.)
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'address_line'?: string;
    /**
     * City/Province
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'city'?: string;
    /**
     * District (optional)
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'district'?: string;
    /**
     * Ward/Commune (optional)
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'ward'?: string;
    /**
     * Postal code (optional, 5-10 digits)
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'postal_code'?: string;
    /**
     * Address type
     * @type {string}
     * @memberof UpdateAddressDto
     */
    'address_type'?: UpdateAddressDtoAddressTypeEnum;
}

export const UpdateAddressDtoAddressTypeEnum = {
    HOME: 'home',
    OFFICE: 'office',
    OTHER: 'other'
} as const;

export type UpdateAddressDtoAddressTypeEnum = typeof UpdateAddressDtoAddressTypeEnum[keyof typeof UpdateAddressDtoAddressTypeEnum];


