/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateReviewDto
 */
export interface UpdateReviewDto {
    /**
     * Rating from 1 to 5 stars
     * @type {number}
     * @memberof UpdateReviewDto
     */
    'rating'?: number;
    /**
     * Review title
     * @type {string}
     * @memberof UpdateReviewDto
     */
    'title'?: string;
    /**
     * Review comment/content
     * @type {string}
     * @memberof UpdateReviewDto
     */
    'comment'?: string;
    /**
     * Array of image URLs
     * @type {Array<string>}
     * @memberof UpdateReviewDto
     */
    'images'?: Array<string>;
}

