/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateProductDto
 */
export interface UpdateProductDto {
    /**
     * Category ID
     * @type {number}
     * @memberof UpdateProductDto
     */
    'category_id'?: number;
    /**
     * Product name
     * @type {string}
     * @memberof UpdateProductDto
     */
    'name'?: string;
    /**
     * Brand name
     * @type {string}
     * @memberof UpdateProductDto
     */
    'brand'?: string;
    /**
     * Model number
     * @type {string}
     * @memberof UpdateProductDto
     */
    'model'?: string;
    /**
     * Product description
     * @type {string}
     * @memberof UpdateProductDto
     */
    'description'?: string;
    /**
     * Product price in VND
     * @type {number}
     * @memberof UpdateProductDto
     */
    'price'?: number;
    /**
     * Compare at price (original price before discount)
     * @type {number}
     * @memberof UpdateProductDto
     */
    'compare_at_price'?: number;
    /**
     * Stock Keeping Unit (unique)
     * @type {string}
     * @memberof UpdateProductDto
     */
    'sku'?: string;
    /**
     * Available stock quantity
     * @type {number}
     * @memberof UpdateProductDto
     */
    'stock_quantity'?: number;
    /**
     * Product specifications in JSON format
     * @type {string}
     * @memberof UpdateProductDto
     */
    'specifications'?: string;
    /**
     * Primary product image URL
     * @type {string}
     * @memberof UpdateProductDto
     */
    'primary_image'?: string;
    /**
     * Additional product images (array of URLs)
     * @type {Array<string>}
     * @memberof UpdateProductDto
     */
    'additional_images'?: Array<string>;
    /**
     * Warranty period in months
     * @type {number}
     * @memberof UpdateProductDto
     */
    'warranty_months'?: number;
    /**
     * SEO meta title
     * @type {string}
     * @memberof UpdateProductDto
     */
    'meta_title'?: string;
    /**
     * SEO meta description
     * @type {string}
     * @memberof UpdateProductDto
     */
    'meta_description'?: string;
    /**
     * Product active status (1 = active, 0 = inactive)
     * @type {number}
     * @memberof UpdateProductDto
     */
    'is_active'?: number;
}

