/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateDiscountDto
 */
export interface UpdateDiscountDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateDiscountDto
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDiscountDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDiscountDto
     */
    'discount_type'?: UpdateDiscountDtoDiscountTypeEnum;
    /**
     * Percentage (1-100) or amount in VND
     * @type {number}
     * @memberof UpdateDiscountDto
     */
    'discount_value'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDiscountDto
     */
    'min_order_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDiscountDto
     */
    'max_discount_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDiscountDto
     */
    'max_uses'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDiscountDto
     */
    'max_uses_per_user'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateDiscountDto
     */
    'starts_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDiscountDto
     */
    'ends_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateDiscountDto
     */
    'is_active'?: boolean;
}

export const UpdateDiscountDtoDiscountTypeEnum = {
    PERCENTAGE: 'percentage',
    FIXED_AMOUNT: 'fixed_amount',
    FREE_SHIPPING: 'free_shipping'
} as const;

export type UpdateDiscountDtoDiscountTypeEnum = typeof UpdateDiscountDtoDiscountTypeEnum[keyof typeof UpdateDiscountDtoDiscountTypeEnum];


