/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateAdminProfileDto
 */
export interface UpdateAdminProfileDto {
    /**
     * Full name of the admin
     * @type {string}
     * @memberof UpdateAdminProfileDto
     */
    'full_name'?: string;
    /**
     * Phone number (10-20 digits)
     * @type {string}
     * @memberof UpdateAdminProfileDto
     */
    'phone'?: string;
}

