/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CreateAddressDto } from '../models';
// @ts-ignore
import { UpdateAddressDto } from '../models';
/**
 * AddressesApi - axios parameter creator
 * @export
 */
export const AddressesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new shipping/billing address for authenticated user. First address is automatically set as default.
         * @summary Create new address
         * @param {CreateAddressDto} createAddressDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerCreate: async (createAddressDto: CreateAddressDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAddressDto' is not null or undefined
            assertParamExists('addressesControllerCreate', 'createAddressDto', createAddressDto)
            const localVarPath = `/api/v1/addresses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAddressDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all addresses for authenticated user. Default address appears first.
         * @summary Get all addresses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/addresses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the default address for authenticated user.
         * @summary Get default address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerFindDefault: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/addresses/default`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a specific address by ID. Validates ownership.
         * @summary Get address by ID
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addressesControllerFindOne', 'id', id)
            const localVarPath = `/api/v1/addresses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete an address. If deleting default address, automatically sets another as default.
         * @summary Delete address
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerRemove: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addressesControllerRemove', 'id', id)
            const localVarPath = `/api/v1/addresses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Set an address as default. Automatically unsets other default addresses.
         * @summary Set address as default
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerSetDefault: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addressesControllerSetDefault', 'id', id)
            const localVarPath = `/api/v1/addresses/{id}/default`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing address. Validates ownership.
         * @summary Update address
         * @param {number} id Address ID
         * @param {UpdateAddressDto} updateAddressDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerUpdate: async (id: number, updateAddressDto: UpdateAddressDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addressesControllerUpdate', 'id', id)
            // verify required parameter 'updateAddressDto' is not null or undefined
            assertParamExists('addressesControllerUpdate', 'updateAddressDto', updateAddressDto)
            const localVarPath = `/api/v1/addresses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateAddressDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AddressesApi - functional programming interface
 * @export
 */
export const AddressesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AddressesApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new shipping/billing address for authenticated user. First address is automatically set as default.
         * @summary Create new address
         * @param {CreateAddressDto} createAddressDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressesControllerCreate(createAddressDto: CreateAddressDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressesControllerCreate(createAddressDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AddressesApi.addressesControllerCreate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get all addresses for authenticated user. Default address appears first.
         * @summary Get all addresses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressesControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressesControllerFindAll(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AddressesApi.addressesControllerFindAll']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get the default address for authenticated user.
         * @summary Get default address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressesControllerFindDefault(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressesControllerFindDefault(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AddressesApi.addressesControllerFindDefault']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get a specific address by ID. Validates ownership.
         * @summary Get address by ID
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressesControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressesControllerFindOne(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AddressesApi.addressesControllerFindOne']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Delete an address. If deleting default address, automatically sets another as default.
         * @summary Delete address
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressesControllerRemove(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressesControllerRemove(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AddressesApi.addressesControllerRemove']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Set an address as default. Automatically unsets other default addresses.
         * @summary Set address as default
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressesControllerSetDefault(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressesControllerSetDefault(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AddressesApi.addressesControllerSetDefault']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Update an existing address. Validates ownership.
         * @summary Update address
         * @param {number} id Address ID
         * @param {UpdateAddressDto} updateAddressDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addressesControllerUpdate(id: number, updateAddressDto: UpdateAddressDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addressesControllerUpdate(id, updateAddressDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AddressesApi.addressesControllerUpdate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * AddressesApi - factory interface
 * @export
 */
export const AddressesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AddressesApiFp(configuration)
    return {
        /**
         * Create a new shipping/billing address for authenticated user. First address is automatically set as default.
         * @summary Create new address
         * @param {CreateAddressDto} createAddressDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerCreate(createAddressDto: CreateAddressDto, options?: any): AxiosPromise<any> {
            return localVarFp.addressesControllerCreate(createAddressDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all addresses for authenticated user. Default address appears first.
         * @summary Get all addresses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerFindAll(options?: any): AxiosPromise<any> {
            return localVarFp.addressesControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * Get the default address for authenticated user.
         * @summary Get default address
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerFindDefault(options?: any): AxiosPromise<void> {
            return localVarFp.addressesControllerFindDefault(options).then((request) => request(axios, basePath));
        },
        /**
         * Get a specific address by ID. Validates ownership.
         * @summary Get address by ID
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerFindOne(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.addressesControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete an address. If deleting default address, automatically sets another as default.
         * @summary Delete address
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerRemove(id: number, options?: any): AxiosPromise<any> {
            return localVarFp.addressesControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Set an address as default. Automatically unsets other default addresses.
         * @summary Set address as default
         * @param {number} id Address ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerSetDefault(id: number, options?: any): AxiosPromise<any> {
            return localVarFp.addressesControllerSetDefault(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing address. Validates ownership.
         * @summary Update address
         * @param {number} id Address ID
         * @param {UpdateAddressDto} updateAddressDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addressesControllerUpdate(id: number, updateAddressDto: UpdateAddressDto, options?: any): AxiosPromise<void> {
            return localVarFp.addressesControllerUpdate(id, updateAddressDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AddressesApi - interface
 * @export
 * @interface AddressesApi
 */
export interface AddressesApiInterface {
    /**
     * Create a new shipping/billing address for authenticated user. First address is automatically set as default.
     * @summary Create new address
     * @param {CreateAddressDto} createAddressDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApiInterface
     */
    addressesControllerCreate(createAddressDto: CreateAddressDto, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Get all addresses for authenticated user. Default address appears first.
     * @summary Get all addresses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApiInterface
     */
    addressesControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Get the default address for authenticated user.
     * @summary Get default address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApiInterface
     */
    addressesControllerFindDefault(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get a specific address by ID. Validates ownership.
     * @summary Get address by ID
     * @param {number} id Address ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApiInterface
     */
    addressesControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Delete an address. If deleting default address, automatically sets another as default.
     * @summary Delete address
     * @param {number} id Address ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApiInterface
     */
    addressesControllerRemove(id: number, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Set an address as default. Automatically unsets other default addresses.
     * @summary Set address as default
     * @param {number} id Address ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApiInterface
     */
    addressesControllerSetDefault(id: number, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Update an existing address. Validates ownership.
     * @summary Update address
     * @param {number} id Address ID
     * @param {UpdateAddressDto} updateAddressDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApiInterface
     */
    addressesControllerUpdate(id: number, updateAddressDto: UpdateAddressDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * AddressesApi - object-oriented interface
 * @export
 * @class AddressesApi
 * @extends {BaseAPI}
 */
export class AddressesApi extends BaseAPI implements AddressesApiInterface {
    /**
     * Create a new shipping/billing address for authenticated user. First address is automatically set as default.
     * @summary Create new address
     * @param {CreateAddressDto} createAddressDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public addressesControllerCreate(createAddressDto: CreateAddressDto, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).addressesControllerCreate(createAddressDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all addresses for authenticated user. Default address appears first.
     * @summary Get all addresses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public addressesControllerFindAll(options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).addressesControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the default address for authenticated user.
     * @summary Get default address
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public addressesControllerFindDefault(options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).addressesControllerFindDefault(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a specific address by ID. Validates ownership.
     * @summary Get address by ID
     * @param {number} id Address ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public addressesControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).addressesControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete an address. If deleting default address, automatically sets another as default.
     * @summary Delete address
     * @param {number} id Address ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public addressesControllerRemove(id: number, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).addressesControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Set an address as default. Automatically unsets other default addresses.
     * @summary Set address as default
     * @param {number} id Address ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public addressesControllerSetDefault(id: number, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).addressesControllerSetDefault(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing address. Validates ownership.
     * @summary Update address
     * @param {number} id Address ID
     * @param {UpdateAddressDto} updateAddressDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddressesApi
     */
    public addressesControllerUpdate(id: number, updateAddressDto: UpdateAddressDto, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).addressesControllerUpdate(id, updateAddressDto, options).then((request) => request(this.axios, this.basePath));
    }
}

