/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { LoginDto } from '../models';
/**
 * AdminAuthApi - axios parameter creator
 * @export
 */
export const AdminAuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Admin login - returns tokens in JSON, no cookies
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthControllerAdminLogin: async (loginDto: LoginDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginDto' is not null or undefined
            assertParamExists('adminAuthControllerAdminLogin', 'loginDto', loginDto)
            const localVarPath = `/api/v1/auth/admin/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Admin logout - token from request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthControllerAdminLogout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/auth/admin/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh admin access token from request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthControllerAdminRefreshToken: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/auth/admin/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminAuthApi - functional programming interface
 * @export
 */
export const AdminAuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminAuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Admin login - returns tokens in JSON, no cookies
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminAuthControllerAdminLogin(loginDto: LoginDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminAuthControllerAdminLogin(loginDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AdminAuthApi.adminAuthControllerAdminLogin']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Admin logout - token from request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminAuthControllerAdminLogout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminAuthControllerAdminLogout(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AdminAuthApi.adminAuthControllerAdminLogout']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh admin access token from request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminAuthControllerAdminRefreshToken(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminAuthControllerAdminRefreshToken(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AdminAuthApi.adminAuthControllerAdminRefreshToken']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * AdminAuthApi - factory interface
 * @export
 */
export const AdminAuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminAuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Admin login - returns tokens in JSON, no cookies
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthControllerAdminLogin(loginDto: LoginDto, options?: any): AxiosPromise<void> {
            return localVarFp.adminAuthControllerAdminLogin(loginDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Admin logout - token from request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthControllerAdminLogout(options?: any): AxiosPromise<void> {
            return localVarFp.adminAuthControllerAdminLogout(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh admin access token from request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthControllerAdminRefreshToken(options?: any): AxiosPromise<void> {
            return localVarFp.adminAuthControllerAdminRefreshToken(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminAuthApi - interface
 * @export
 * @interface AdminAuthApi
 */
export interface AdminAuthApiInterface {
    /**
     * 
     * @summary Admin login - returns tokens in JSON, no cookies
     * @param {LoginDto} loginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApiInterface
     */
    adminAuthControllerAdminLogin(loginDto: LoginDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Admin logout - token from request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApiInterface
     */
    adminAuthControllerAdminLogout(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Refresh admin access token from request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApiInterface
     */
    adminAuthControllerAdminRefreshToken(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * AdminAuthApi - object-oriented interface
 * @export
 * @class AdminAuthApi
 * @extends {BaseAPI}
 */
export class AdminAuthApi extends BaseAPI implements AdminAuthApiInterface {
    /**
     * 
     * @summary Admin login - returns tokens in JSON, no cookies
     * @param {LoginDto} loginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApi
     */
    public adminAuthControllerAdminLogin(loginDto: LoginDto, options?: RawAxiosRequestConfig) {
        return AdminAuthApiFp(this.configuration).adminAuthControllerAdminLogin(loginDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Admin logout - token from request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApi
     */
    public adminAuthControllerAdminLogout(options?: RawAxiosRequestConfig) {
        return AdminAuthApiFp(this.configuration).adminAuthControllerAdminLogout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh admin access token from request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApi
     */
    public adminAuthControllerAdminRefreshToken(options?: RawAxiosRequestConfig) {
        return AdminAuthApiFp(this.configuration).adminAuthControllerAdminRefreshToken(options).then((request) => request(this.axios, this.basePath));
    }
}

