/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { AddToCartDto } from '../models';
// @ts-ignore
import { UpdateCartItemDto } from '../models';
/**
 * CartApi - axios parameter creator
 * @export
 */
export const CartApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add a product to cart or increase quantity if already exists. Requires authentication. Validates stock availability.
         * @summary Add product to cart
         * @param {AddToCartDto} addToCartDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerAddToCart: async (addToCartDto: AddToCartDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addToCartDto' is not null or undefined
            assertParamExists('cartControllerAddToCart', 'addToCartDto', addToCartDto)
            const localVarPath = `/api/v1/cart/items`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addToCartDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove all items from current cart.
         * @summary Clear cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerClearCart: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/cart`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve current cart for authenticated user. Returns null if no cart exists.
         * @summary Get current cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerGetCart: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/cart`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Merge guest session cart into authenticated user cart after login. Called automatically by auth service.
         * @summary Merge guest cart into user cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerMergeCart: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/cart/merge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a specific item from cart by item ID.
         * @summary Remove item from cart
         * @param {number} id Cart item ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerRemoveCartItem: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cartControllerRemoveCartItem', 'id', id)
            const localVarPath = `/api/v1/cart/items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update quantity of existing cart item. Validates stock and ownership.
         * @summary Update cart item quantity
         * @param {number} id Cart item ID
         * @param {UpdateCartItemDto} updateCartItemDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerUpdateCartItem: async (id: number, updateCartItemDto: UpdateCartItemDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cartControllerUpdateCartItem', 'id', id)
            // verify required parameter 'updateCartItemDto' is not null or undefined
            assertParamExists('cartControllerUpdateCartItem', 'updateCartItemDto', updateCartItemDto)
            const localVarPath = `/api/v1/cart/items/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCartItemDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Validate cart items before checkout. Checks product availability, stock, and price changes.
         * @summary Validate cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerValidateCart: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/cart/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CartApi - functional programming interface
 * @export
 */
export const CartApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CartApiAxiosParamCreator(configuration)
    return {
        /**
         * Add a product to cart or increase quantity if already exists. Requires authentication. Validates stock availability.
         * @summary Add product to cart
         * @param {AddToCartDto} addToCartDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerAddToCart(addToCartDto: AddToCartDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerAddToCart(addToCartDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CartApi.cartControllerAddToCart']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Remove all items from current cart.
         * @summary Clear cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerClearCart(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerClearCart(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CartApi.cartControllerClearCart']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Retrieve current cart for authenticated user. Returns null if no cart exists.
         * @summary Get current cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerGetCart(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerGetCart(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CartApi.cartControllerGetCart']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Merge guest session cart into authenticated user cart after login. Called automatically by auth service.
         * @summary Merge guest cart into user cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerMergeCart(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerMergeCart(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CartApi.cartControllerMergeCart']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Remove a specific item from cart by item ID.
         * @summary Remove item from cart
         * @param {number} id Cart item ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerRemoveCartItem(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerRemoveCartItem(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CartApi.cartControllerRemoveCartItem']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Update quantity of existing cart item. Validates stock and ownership.
         * @summary Update cart item quantity
         * @param {number} id Cart item ID
         * @param {UpdateCartItemDto} updateCartItemDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerUpdateCartItem(id: number, updateCartItemDto: UpdateCartItemDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerUpdateCartItem(id, updateCartItemDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CartApi.cartControllerUpdateCartItem']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Validate cart items before checkout. Checks product availability, stock, and price changes.
         * @summary Validate cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cartControllerValidateCart(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cartControllerValidateCart(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CartApi.cartControllerValidateCart']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * CartApi - factory interface
 * @export
 */
export const CartApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CartApiFp(configuration)
    return {
        /**
         * Add a product to cart or increase quantity if already exists. Requires authentication. Validates stock availability.
         * @summary Add product to cart
         * @param {AddToCartDto} addToCartDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerAddToCart(addToCartDto: AddToCartDto, options?: any): AxiosPromise<void> {
            return localVarFp.cartControllerAddToCart(addToCartDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove all items from current cart.
         * @summary Clear cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerClearCart(options?: any): AxiosPromise<void> {
            return localVarFp.cartControllerClearCart(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve current cart for authenticated user. Returns null if no cart exists.
         * @summary Get current cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerGetCart(options?: any): AxiosPromise<object> {
            return localVarFp.cartControllerGetCart(options).then((request) => request(axios, basePath));
        },
        /**
         * Merge guest session cart into authenticated user cart after login. Called automatically by auth service.
         * @summary Merge guest cart into user cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerMergeCart(options?: any): AxiosPromise<void> {
            return localVarFp.cartControllerMergeCart(options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a specific item from cart by item ID.
         * @summary Remove item from cart
         * @param {number} id Cart item ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerRemoveCartItem(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.cartControllerRemoveCartItem(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Update quantity of existing cart item. Validates stock and ownership.
         * @summary Update cart item quantity
         * @param {number} id Cart item ID
         * @param {UpdateCartItemDto} updateCartItemDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerUpdateCartItem(id: number, updateCartItemDto: UpdateCartItemDto, options?: any): AxiosPromise<void> {
            return localVarFp.cartControllerUpdateCartItem(id, updateCartItemDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Validate cart items before checkout. Checks product availability, stock, and price changes.
         * @summary Validate cart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cartControllerValidateCart(options?: any): AxiosPromise<any> {
            return localVarFp.cartControllerValidateCart(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CartApi - interface
 * @export
 * @interface CartApi
 */
export interface CartApiInterface {
    /**
     * Add a product to cart or increase quantity if already exists. Requires authentication. Validates stock availability.
     * @summary Add product to cart
     * @param {AddToCartDto} addToCartDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApiInterface
     */
    cartControllerAddToCart(addToCartDto: AddToCartDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Remove all items from current cart.
     * @summary Clear cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApiInterface
     */
    cartControllerClearCart(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Retrieve current cart for authenticated user. Returns null if no cart exists.
     * @summary Get current cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApiInterface
     */
    cartControllerGetCart(options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * Merge guest session cart into authenticated user cart after login. Called automatically by auth service.
     * @summary Merge guest cart into user cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApiInterface
     */
    cartControllerMergeCart(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Remove a specific item from cart by item ID.
     * @summary Remove item from cart
     * @param {number} id Cart item ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApiInterface
     */
    cartControllerRemoveCartItem(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Update quantity of existing cart item. Validates stock and ownership.
     * @summary Update cart item quantity
     * @param {number} id Cart item ID
     * @param {UpdateCartItemDto} updateCartItemDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApiInterface
     */
    cartControllerUpdateCartItem(id: number, updateCartItemDto: UpdateCartItemDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Validate cart items before checkout. Checks product availability, stock, and price changes.
     * @summary Validate cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApiInterface
     */
    cartControllerValidateCart(options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * CartApi - object-oriented interface
 * @export
 * @class CartApi
 * @extends {BaseAPI}
 */
export class CartApi extends BaseAPI implements CartApiInterface {
    /**
     * Add a product to cart or increase quantity if already exists. Requires authentication. Validates stock availability.
     * @summary Add product to cart
     * @param {AddToCartDto} addToCartDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApi
     */
    public cartControllerAddToCart(addToCartDto: AddToCartDto, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerAddToCart(addToCartDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove all items from current cart.
     * @summary Clear cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApi
     */
    public cartControllerClearCart(options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerClearCart(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve current cart for authenticated user. Returns null if no cart exists.
     * @summary Get current cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApi
     */
    public cartControllerGetCart(options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerGetCart(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Merge guest session cart into authenticated user cart after login. Called automatically by auth service.
     * @summary Merge guest cart into user cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApi
     */
    public cartControllerMergeCart(options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerMergeCart(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove a specific item from cart by item ID.
     * @summary Remove item from cart
     * @param {number} id Cart item ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApi
     */
    public cartControllerRemoveCartItem(id: number, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerRemoveCartItem(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update quantity of existing cart item. Validates stock and ownership.
     * @summary Update cart item quantity
     * @param {number} id Cart item ID
     * @param {UpdateCartItemDto} updateCartItemDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApi
     */
    public cartControllerUpdateCartItem(id: number, updateCartItemDto: UpdateCartItemDto, options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerUpdateCartItem(id, updateCartItemDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Validate cart items before checkout. Checks product availability, stock, and price changes.
     * @summary Validate cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CartApi
     */
    public cartControllerValidateCart(options?: RawAxiosRequestConfig) {
        return CartApiFp(this.configuration).cartControllerValidateCart(options).then((request) => request(this.axios, this.basePath));
    }
}

