/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CategoriesControllerReorderRequest } from '../models';
// @ts-ignore
import { CreateCategoryDto } from '../models';
// @ts-ignore
import { UpdateCategoryDto } from '../models';
/**
 * CategoriesApi - axios parameter creator
 * @export
 */
export const CategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new category (Admin only)
         * @param {CreateCategoryDto} createCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerCreate: async (createCategoryDto: CreateCategoryDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCategoryDto' is not null or undefined
            assertParamExists('categoriesControllerCreate', 'createCategoryDto', createCategoryDto)
            const localVarPath = `/api/v1/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCategoryDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all categories with filters and pagination
         * @param {string} [search] Search by category name
         * @param {number} [parentId] Filter by parent category ID (null for root categories)
         * @param {boolean} [isActive] Filter by active status
         * @param {boolean} [includeProductsCount] Include product count for each category
         * @param {CategoriesControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {CategoriesControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerFindAll: async (search?: string, parentId?: number, isActive?: boolean, includeProductsCount?: boolean, sortBy?: CategoriesControllerFindAllSortByEnum, sortOrder?: CategoriesControllerFindAllSortOrderEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (parentId !== undefined) {
                localVarQueryParameter['parent_id'] = parentId;
            }

            if (isActive !== undefined) {
                localVarQueryParameter['is_active'] = isActive;
            }

            if (includeProductsCount !== undefined) {
                localVarQueryParameter['include_products_count'] = includeProductsCount;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a category by slug (SEO-friendly)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerFindBySlug: async (slug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('categoriesControllerFindBySlug', 'slug', slug)
            const localVarPath = `/api/v1/categories/slug/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a category by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('categoriesControllerFindOne', 'id', id)
            const localVarPath = `/api/v1/categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get category tree structure (hierarchical)
         * @param {boolean} [includeInactive] Include inactive categories (admin only)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerGetCategoryTree: async (includeInactive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/categories/tree`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (includeInactive !== undefined) {
                localVarQueryParameter['include_inactive'] = includeInactive;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get root categories (no parent)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerGetRootCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/categories/roots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a category - soft delete (Admin only)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerRemove: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('categoriesControllerRemove', 'id', id)
            const localVarPath = `/api/v1/categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reorder categories (Admin only)
         * @param {CategoriesControllerReorderRequest} categoriesControllerReorderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerReorder: async (categoriesControllerReorderRequest: CategoriesControllerReorderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'categoriesControllerReorderRequest' is not null or undefined
            assertParamExists('categoriesControllerReorder', 'categoriesControllerReorderRequest', categoriesControllerReorderRequest)
            const localVarPath = `/api/v1/categories/reorder`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(categoriesControllerReorderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a category (Admin only)
         * @param {number} id 
         * @param {UpdateCategoryDto} updateCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerUpdate: async (id: number, updateCategoryDto: UpdateCategoryDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('categoriesControllerUpdate', 'id', id)
            // verify required parameter 'updateCategoryDto' is not null or undefined
            assertParamExists('categoriesControllerUpdate', 'updateCategoryDto', updateCategoryDto)
            const localVarPath = `/api/v1/categories/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCategoryDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoriesApi - functional programming interface
 * @export
 */
export const CategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new category (Admin only)
         * @param {CreateCategoryDto} createCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerCreate(createCategoryDto: CreateCategoryDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerCreate(createCategoryDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerCreate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get all categories with filters and pagination
         * @param {string} [search] Search by category name
         * @param {number} [parentId] Filter by parent category ID (null for root categories)
         * @param {boolean} [isActive] Filter by active status
         * @param {boolean} [includeProductsCount] Include product count for each category
         * @param {CategoriesControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {CategoriesControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerFindAll(search?: string, parentId?: number, isActive?: boolean, includeProductsCount?: boolean, sortBy?: CategoriesControllerFindAllSortByEnum, sortOrder?: CategoriesControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerFindAll(search, parentId, isActive, includeProductsCount, sortBy, sortOrder, page, limit, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerFindAll']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get a category by slug (SEO-friendly)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerFindBySlug(slug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerFindBySlug(slug, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerFindBySlug']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get a category by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerFindOne(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerFindOne']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get category tree structure (hierarchical)
         * @param {boolean} [includeInactive] Include inactive categories (admin only)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerGetCategoryTree(includeInactive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerGetCategoryTree(includeInactive, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerGetCategoryTree']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get root categories (no parent)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerGetRootCategories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerGetRootCategories(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerGetRootCategories']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a category - soft delete (Admin only)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerRemove(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerRemove(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerRemove']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Reorder categories (Admin only)
         * @param {CategoriesControllerReorderRequest} categoriesControllerReorderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerReorder(categoriesControllerReorderRequest: CategoriesControllerReorderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerReorder(categoriesControllerReorderRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerReorder']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Update a category (Admin only)
         * @param {number} id 
         * @param {UpdateCategoryDto} updateCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoriesControllerUpdate(id: number, updateCategoryDto: UpdateCategoryDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoriesControllerUpdate(id, updateCategoryDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['CategoriesApi.categoriesControllerUpdate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * CategoriesApi - factory interface
 * @export
 */
export const CategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoriesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new category (Admin only)
         * @param {CreateCategoryDto} createCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerCreate(createCategoryDto: CreateCategoryDto, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerCreate(createCategoryDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all categories with filters and pagination
         * @param {string} [search] Search by category name
         * @param {number} [parentId] Filter by parent category ID (null for root categories)
         * @param {boolean} [isActive] Filter by active status
         * @param {boolean} [includeProductsCount] Include product count for each category
         * @param {CategoriesControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {CategoriesControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerFindAll(search?: string, parentId?: number, isActive?: boolean, includeProductsCount?: boolean, sortBy?: CategoriesControllerFindAllSortByEnum, sortOrder?: CategoriesControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerFindAll(search, parentId, isActive, includeProductsCount, sortBy, sortOrder, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a category by slug (SEO-friendly)
         * @param {string} slug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerFindBySlug(slug: string, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerFindBySlug(slug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a category by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerFindOne(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get category tree structure (hierarchical)
         * @param {boolean} [includeInactive] Include inactive categories (admin only)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerGetCategoryTree(includeInactive?: boolean, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerGetCategoryTree(includeInactive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get root categories (no parent)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerGetRootCategories(options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerGetRootCategories(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a category - soft delete (Admin only)
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerRemove(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reorder categories (Admin only)
         * @param {CategoriesControllerReorderRequest} categoriesControllerReorderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerReorder(categoriesControllerReorderRequest: CategoriesControllerReorderRequest, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerReorder(categoriesControllerReorderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a category (Admin only)
         * @param {number} id 
         * @param {UpdateCategoryDto} updateCategoryDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoriesControllerUpdate(id: number, updateCategoryDto: UpdateCategoryDto, options?: any): AxiosPromise<void> {
            return localVarFp.categoriesControllerUpdate(id, updateCategoryDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CategoriesApi - interface
 * @export
 * @interface CategoriesApi
 */
export interface CategoriesApiInterface {
    /**
     * 
     * @summary Create a new category (Admin only)
     * @param {CreateCategoryDto} createCategoryDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerCreate(createCategoryDto: CreateCategoryDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all categories with filters and pagination
     * @param {string} [search] Search by category name
     * @param {number} [parentId] Filter by parent category ID (null for root categories)
     * @param {boolean} [isActive] Filter by active status
     * @param {boolean} [includeProductsCount] Include product count for each category
     * @param {CategoriesControllerFindAllSortByEnum} [sortBy] Sort by field
     * @param {CategoriesControllerFindAllSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerFindAll(search?: string, parentId?: number, isActive?: boolean, includeProductsCount?: boolean, sortBy?: CategoriesControllerFindAllSortByEnum, sortOrder?: CategoriesControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a category by slug (SEO-friendly)
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerFindBySlug(slug: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a category by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get category tree structure (hierarchical)
     * @param {boolean} [includeInactive] Include inactive categories (admin only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerGetCategoryTree(includeInactive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get root categories (no parent)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerGetRootCategories(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Delete a category - soft delete (Admin only)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerRemove(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Reorder categories (Admin only)
     * @param {CategoriesControllerReorderRequest} categoriesControllerReorderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerReorder(categoriesControllerReorderRequest: CategoriesControllerReorderRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Update a category (Admin only)
     * @param {number} id 
     * @param {UpdateCategoryDto} updateCategoryDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApiInterface
     */
    categoriesControllerUpdate(id: number, updateCategoryDto: UpdateCategoryDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * CategoriesApi - object-oriented interface
 * @export
 * @class CategoriesApi
 * @extends {BaseAPI}
 */
export class CategoriesApi extends BaseAPI implements CategoriesApiInterface {
    /**
     * 
     * @summary Create a new category (Admin only)
     * @param {CreateCategoryDto} createCategoryDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerCreate(createCategoryDto: CreateCategoryDto, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerCreate(createCategoryDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all categories with filters and pagination
     * @param {string} [search] Search by category name
     * @param {number} [parentId] Filter by parent category ID (null for root categories)
     * @param {boolean} [isActive] Filter by active status
     * @param {boolean} [includeProductsCount] Include product count for each category
     * @param {CategoriesControllerFindAllSortByEnum} [sortBy] Sort by field
     * @param {CategoriesControllerFindAllSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerFindAll(search?: string, parentId?: number, isActive?: boolean, includeProductsCount?: boolean, sortBy?: CategoriesControllerFindAllSortByEnum, sortOrder?: CategoriesControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerFindAll(search, parentId, isActive, includeProductsCount, sortBy, sortOrder, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a category by slug (SEO-friendly)
     * @param {string} slug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerFindBySlug(slug: string, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerFindBySlug(slug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a category by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get category tree structure (hierarchical)
     * @param {boolean} [includeInactive] Include inactive categories (admin only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerGetCategoryTree(includeInactive?: boolean, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerGetCategoryTree(includeInactive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get root categories (no parent)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerGetRootCategories(options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerGetRootCategories(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a category - soft delete (Admin only)
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerRemove(id: number, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reorder categories (Admin only)
     * @param {CategoriesControllerReorderRequest} categoriesControllerReorderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerReorder(categoriesControllerReorderRequest: CategoriesControllerReorderRequest, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerReorder(categoriesControllerReorderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a category (Admin only)
     * @param {number} id 
     * @param {UpdateCategoryDto} updateCategoryDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    public categoriesControllerUpdate(id: number, updateCategoryDto: UpdateCategoryDto, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).categoriesControllerUpdate(id, updateCategoryDto, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const CategoriesControllerFindAllSortByEnum = {
    DISPLAY_ORDER: 'display_order',
    NAME: 'name',
    CREATED_AT: 'created_at'
} as const;
export type CategoriesControllerFindAllSortByEnum = typeof CategoriesControllerFindAllSortByEnum[keyof typeof CategoriesControllerFindAllSortByEnum];
/**
 * @export
 */
export const CategoriesControllerFindAllSortOrderEnum = {
    ASC: 'asc',
    DESC: 'desc'
} as const;
export type CategoriesControllerFindAllSortOrderEnum = typeof CategoriesControllerFindAllSortOrderEnum[keyof typeof CategoriesControllerFindAllSortOrderEnum];
