/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * DashboardApi - axios parameter creator
 * @export
 */
export const DashboardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get category performance
         * @param {DashboardControllerGetCategoryPerformancePeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetCategoryPerformance: async (period?: DashboardControllerGetCategoryPerformancePeriodEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/category-performance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get low stock products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetLowStock: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/low-stock`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get orders grouped by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetOrdersByStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/orders-by-status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get dashboard overview
         * @param {DashboardControllerGetOverviewPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetOverview: async (period?: DashboardControllerGetOverviewPeriodEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/overview`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get recent activities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetRecentActivities: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/recent-activities`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get revenue chart data
         * @param {DashboardControllerGetRevenueChartPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetRevenueChart: async (period?: DashboardControllerGetRevenueChartPeriodEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/revenue-chart`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get top customers by spending
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetTopCustomers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/top-customers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get top selling products
         * @param {DashboardControllerGetTopProductsPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetTopProducts: async (period?: DashboardControllerGetTopProductsPeriodEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/top-products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DashboardApi - functional programming interface
 * @export
 */
export const DashboardApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DashboardApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get category performance
         * @param {DashboardControllerGetCategoryPerformancePeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetCategoryPerformance(period?: DashboardControllerGetCategoryPerformancePeriodEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetCategoryPerformance(period, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetCategoryPerformance']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get low stock products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetLowStock(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetLowStock(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetLowStock']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get orders grouped by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetOrdersByStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetOrdersByStatus(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetOrdersByStatus']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get dashboard overview
         * @param {DashboardControllerGetOverviewPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetOverview(period?: DashboardControllerGetOverviewPeriodEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetOverview(period, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetOverview']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get recent activities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetRecentActivities(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetRecentActivities(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetRecentActivities']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get revenue chart data
         * @param {DashboardControllerGetRevenueChartPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetRevenueChart(period?: DashboardControllerGetRevenueChartPeriodEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetRevenueChart(period, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetRevenueChart']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get top customers by spending
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetTopCustomers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetTopCustomers(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetTopCustomers']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get top selling products
         * @param {DashboardControllerGetTopProductsPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboardControllerGetTopProducts(period?: DashboardControllerGetTopProductsPeriodEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboardControllerGetTopProducts(period, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DashboardApi.dashboardControllerGetTopProducts']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * DashboardApi - factory interface
 * @export
 */
export const DashboardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DashboardApiFp(configuration)
    return {
        /**
         * 
         * @summary Get category performance
         * @param {DashboardControllerGetCategoryPerformancePeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetCategoryPerformance(period?: DashboardControllerGetCategoryPerformancePeriodEnum, options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetCategoryPerformance(period, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get low stock products
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetLowStock(options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetLowStock(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get orders grouped by status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetOrdersByStatus(options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetOrdersByStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get dashboard overview
         * @param {DashboardControllerGetOverviewPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetOverview(period?: DashboardControllerGetOverviewPeriodEnum, options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetOverview(period, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get recent activities
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetRecentActivities(options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetRecentActivities(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get revenue chart data
         * @param {DashboardControllerGetRevenueChartPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetRevenueChart(period?: DashboardControllerGetRevenueChartPeriodEnum, options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetRevenueChart(period, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get top customers by spending
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetTopCustomers(options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetTopCustomers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get top selling products
         * @param {DashboardControllerGetTopProductsPeriodEnum} [period] Time period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboardControllerGetTopProducts(period?: DashboardControllerGetTopProductsPeriodEnum, options?: any): AxiosPromise<void> {
            return localVarFp.dashboardControllerGetTopProducts(period, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DashboardApi - interface
 * @export
 * @interface DashboardApi
 */
export interface DashboardApiInterface {
    /**
     * 
     * @summary Get category performance
     * @param {DashboardControllerGetCategoryPerformancePeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetCategoryPerformance(period?: DashboardControllerGetCategoryPerformancePeriodEnum, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get low stock products
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetLowStock(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get orders grouped by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetOrdersByStatus(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get dashboard overview
     * @param {DashboardControllerGetOverviewPeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetOverview(period?: DashboardControllerGetOverviewPeriodEnum, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get recent activities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetRecentActivities(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get revenue chart data
     * @param {DashboardControllerGetRevenueChartPeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetRevenueChart(period?: DashboardControllerGetRevenueChartPeriodEnum, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get top customers by spending
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetTopCustomers(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get top selling products
     * @param {DashboardControllerGetTopProductsPeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    dashboardControllerGetTopProducts(period?: DashboardControllerGetTopProductsPeriodEnum, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * DashboardApi - object-oriented interface
 * @export
 * @class DashboardApi
 * @extends {BaseAPI}
 */
export class DashboardApi extends BaseAPI implements DashboardApiInterface {
    /**
     * 
     * @summary Get category performance
     * @param {DashboardControllerGetCategoryPerformancePeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetCategoryPerformance(period?: DashboardControllerGetCategoryPerformancePeriodEnum, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetCategoryPerformance(period, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get low stock products
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetLowStock(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetLowStock(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get orders grouped by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetOrdersByStatus(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetOrdersByStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get dashboard overview
     * @param {DashboardControllerGetOverviewPeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetOverview(period?: DashboardControllerGetOverviewPeriodEnum, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetOverview(period, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get recent activities
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetRecentActivities(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetRecentActivities(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get revenue chart data
     * @param {DashboardControllerGetRevenueChartPeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetRevenueChart(period?: DashboardControllerGetRevenueChartPeriodEnum, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetRevenueChart(period, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get top customers by spending
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetTopCustomers(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetTopCustomers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get top selling products
     * @param {DashboardControllerGetTopProductsPeriodEnum} [period] Time period
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public dashboardControllerGetTopProducts(period?: DashboardControllerGetTopProductsPeriodEnum, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).dashboardControllerGetTopProducts(period, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const DashboardControllerGetCategoryPerformancePeriodEnum = {
    TODAY: 'today',
    WEEK: 'week',
    MONTH: 'month',
    YEAR: 'year'
} as const;
export type DashboardControllerGetCategoryPerformancePeriodEnum = typeof DashboardControllerGetCategoryPerformancePeriodEnum[keyof typeof DashboardControllerGetCategoryPerformancePeriodEnum];
/**
 * @export
 */
export const DashboardControllerGetOverviewPeriodEnum = {
    TODAY: 'today',
    WEEK: 'week',
    MONTH: 'month',
    YEAR: 'year'
} as const;
export type DashboardControllerGetOverviewPeriodEnum = typeof DashboardControllerGetOverviewPeriodEnum[keyof typeof DashboardControllerGetOverviewPeriodEnum];
/**
 * @export
 */
export const DashboardControllerGetRevenueChartPeriodEnum = {
    TODAY: 'today',
    WEEK: 'week',
    MONTH: 'month',
    YEAR: 'year'
} as const;
export type DashboardControllerGetRevenueChartPeriodEnum = typeof DashboardControllerGetRevenueChartPeriodEnum[keyof typeof DashboardControllerGetRevenueChartPeriodEnum];
/**
 * @export
 */
export const DashboardControllerGetTopProductsPeriodEnum = {
    TODAY: 'today',
    WEEK: 'week',
    MONTH: 'month',
    YEAR: 'year'
} as const;
export type DashboardControllerGetTopProductsPeriodEnum = typeof DashboardControllerGetTopProductsPeriodEnum[keyof typeof DashboardControllerGetTopProductsPeriodEnum];
