/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CreateDiscountDto } from '../models';
// @ts-ignore
import { UpdateDiscountDto } from '../models';
// @ts-ignore
import { ValidateDiscountDto } from '../models';
/**
 * DiscountsApi - axios parameter creator
 * @export
 */
export const DiscountsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create discount code (Admin)
         * @param {CreateDiscountDto} createDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerCreate: async (createDiscountDto: CreateDiscountDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createDiscountDto' is not null or undefined
            assertParamExists('discountsControllerCreate', 'createDiscountDto', createDiscountDto)
            const localVarPath = `/api/v1/discounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDiscountDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all discount codes (Admin)
         * @param {string} [page] 
         * @param {string} [limit] 
         * @param {DiscountsControllerFindAllStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerFindAll: async (page?: string, limit?: string, status?: DiscountsControllerFindAllStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/discounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get discount by ID (Admin)
         * @param {number} id Discount ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('discountsControllerFindOne', 'id', id)
            const localVarPath = `/api/v1/discounts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get my discount usage history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerGetMyUsage: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/discounts/my-usage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get discount statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerGetStatistics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/discounts/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete discount code (Admin)
         * @param {number} id Discount ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerRemove: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('discountsControllerRemove', 'id', id)
            const localVarPath = `/api/v1/discounts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update discount code (Admin)
         * @param {number} id Discount ID
         * @param {UpdateDiscountDto} updateDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerUpdate: async (id: number, updateDiscountDto: UpdateDiscountDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('discountsControllerUpdate', 'id', id)
            // verify required parameter 'updateDiscountDto' is not null or undefined
            assertParamExists('discountsControllerUpdate', 'updateDiscountDto', updateDiscountDto)
            const localVarPath = `/api/v1/discounts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateDiscountDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate discount code
         * @param {ValidateDiscountDto} validateDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerValidate: async (validateDiscountDto: ValidateDiscountDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'validateDiscountDto' is not null or undefined
            assertParamExists('discountsControllerValidate', 'validateDiscountDto', validateDiscountDto)
            const localVarPath = `/api/v1/discounts/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(validateDiscountDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DiscountsApi - functional programming interface
 * @export
 */
export const DiscountsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DiscountsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create discount code (Admin)
         * @param {CreateDiscountDto} createDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerCreate(createDiscountDto: CreateDiscountDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerCreate(createDiscountDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerCreate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get all discount codes (Admin)
         * @param {string} [page] 
         * @param {string} [limit] 
         * @param {DiscountsControllerFindAllStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerFindAll(page?: string, limit?: string, status?: DiscountsControllerFindAllStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerFindAll(page, limit, status, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerFindAll']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get discount by ID (Admin)
         * @param {number} id Discount ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerFindOne(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerFindOne']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get my discount usage history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerGetMyUsage(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerGetMyUsage(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerGetMyUsage']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get discount statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerGetStatistics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerGetStatistics(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerGetStatistics']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Delete discount code (Admin)
         * @param {number} id Discount ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerRemove(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerRemove(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerRemove']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Update discount code (Admin)
         * @param {number} id Discount ID
         * @param {UpdateDiscountDto} updateDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerUpdate(id: number, updateDiscountDto: UpdateDiscountDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerUpdate(id, updateDiscountDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerUpdate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Validate discount code
         * @param {ValidateDiscountDto} validateDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async discountsControllerValidate(validateDiscountDto: ValidateDiscountDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.discountsControllerValidate(validateDiscountDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DiscountsApi.discountsControllerValidate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * DiscountsApi - factory interface
 * @export
 */
export const DiscountsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DiscountsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create discount code (Admin)
         * @param {CreateDiscountDto} createDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerCreate(createDiscountDto: CreateDiscountDto, options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerCreate(createDiscountDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all discount codes (Admin)
         * @param {string} [page] 
         * @param {string} [limit] 
         * @param {DiscountsControllerFindAllStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerFindAll(page?: string, limit?: string, status?: DiscountsControllerFindAllStatusEnum, options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerFindAll(page, limit, status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get discount by ID (Admin)
         * @param {number} id Discount ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerFindOne(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get my discount usage history
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerGetMyUsage(options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerGetMyUsage(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get discount statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerGetStatistics(options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerGetStatistics(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete discount code (Admin)
         * @param {number} id Discount ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerRemove(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update discount code (Admin)
         * @param {number} id Discount ID
         * @param {UpdateDiscountDto} updateDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerUpdate(id: number, updateDiscountDto: UpdateDiscountDto, options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerUpdate(id, updateDiscountDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate discount code
         * @param {ValidateDiscountDto} validateDiscountDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        discountsControllerValidate(validateDiscountDto: ValidateDiscountDto, options?: any): AxiosPromise<void> {
            return localVarFp.discountsControllerValidate(validateDiscountDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DiscountsApi - interface
 * @export
 * @interface DiscountsApi
 */
export interface DiscountsApiInterface {
    /**
     * 
     * @summary Create discount code (Admin)
     * @param {CreateDiscountDto} createDiscountDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerCreate(createDiscountDto: CreateDiscountDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all discount codes (Admin)
     * @param {string} [page] 
     * @param {string} [limit] 
     * @param {DiscountsControllerFindAllStatusEnum} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerFindAll(page?: string, limit?: string, status?: DiscountsControllerFindAllStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get discount by ID (Admin)
     * @param {number} id Discount ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get my discount usage history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerGetMyUsage(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get discount statistics (Admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerGetStatistics(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Delete discount code (Admin)
     * @param {number} id Discount ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerRemove(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Update discount code (Admin)
     * @param {number} id Discount ID
     * @param {UpdateDiscountDto} updateDiscountDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerUpdate(id: number, updateDiscountDto: UpdateDiscountDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Validate discount code
     * @param {ValidateDiscountDto} validateDiscountDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApiInterface
     */
    discountsControllerValidate(validateDiscountDto: ValidateDiscountDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * DiscountsApi - object-oriented interface
 * @export
 * @class DiscountsApi
 * @extends {BaseAPI}
 */
export class DiscountsApi extends BaseAPI implements DiscountsApiInterface {
    /**
     * 
     * @summary Create discount code (Admin)
     * @param {CreateDiscountDto} createDiscountDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerCreate(createDiscountDto: CreateDiscountDto, options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerCreate(createDiscountDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all discount codes (Admin)
     * @param {string} [page] 
     * @param {string} [limit] 
     * @param {DiscountsControllerFindAllStatusEnum} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerFindAll(page?: string, limit?: string, status?: DiscountsControllerFindAllStatusEnum, options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerFindAll(page, limit, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get discount by ID (Admin)
     * @param {number} id Discount ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get my discount usage history
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerGetMyUsage(options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerGetMyUsage(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get discount statistics (Admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerGetStatistics(options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerGetStatistics(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete discount code (Admin)
     * @param {number} id Discount ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerRemove(id: number, options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update discount code (Admin)
     * @param {number} id Discount ID
     * @param {UpdateDiscountDto} updateDiscountDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerUpdate(id: number, updateDiscountDto: UpdateDiscountDto, options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerUpdate(id, updateDiscountDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Validate discount code
     * @param {ValidateDiscountDto} validateDiscountDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiscountsApi
     */
    public discountsControllerValidate(validateDiscountDto: ValidateDiscountDto, options?: RawAxiosRequestConfig) {
        return DiscountsApiFp(this.configuration).discountsControllerValidate(validateDiscountDto, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const DiscountsControllerFindAllStatusEnum = {
    ALL: 'all',
    ACTIVE: 'active',
    EXPIRED: 'expired',
    INACTIVE: 'inactive'
} as const;
export type DiscountsControllerFindAllStatusEnum = typeof DiscountsControllerFindAllStatusEnum[keyof typeof DiscountsControllerFindAllStatusEnum];
