/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { CreateOrderDto } from '../models';
// @ts-ignore
import { UpdateOrderStatusDto } from '../models';
/**
 * OrdersApi - axios parameter creator
 * @export
 */
export const OrdersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancel order. Only pending or confirmed orders can be cancelled by customer.
         * @summary Cancel order
         * @param {number} id Order ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerCancel: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ordersControllerCancel', 'id', id)
            const localVarPath = `/api/v1/orders/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new order from current cart. Validates cart, addresses, stock. Clears cart after successful order.
         * @summary Create order from cart
         * @param {CreateOrderDto} createOrderDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerCreate: async (createOrderDto: CreateOrderDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createOrderDto' is not null or undefined
            assertParamExists('ordersControllerCreate', 'createOrderDto', createOrderDto)
            const localVarPath = `/api/v1/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createOrderDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all orders for authenticated user with filters and pagination.
         * @summary Get all orders
         * @param {OrdersControllerFindAllStatusEnum} [status] Filter by order status
         * @param {string} [search] Search by order number, customer name, email
         * @param {OrdersControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {OrdersControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindAll: async (status?: OrdersControllerFindAllStatusEnum, search?: string, sortBy?: OrdersControllerFindAllSortByEnum, sortOrder?: OrdersControllerFindAllSortOrderEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all orders from all users with filters and pagination. Admin only.
         * @summary Get all orders (Admin)
         * @param {OrdersControllerFindAllAdminStatusEnum} [status] Filter by order status
         * @param {string} [search] Search by order number, customer name, email
         * @param {OrdersControllerFindAllAdminSortByEnum} [sortBy] Sort by field
         * @param {OrdersControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindAllAdmin: async (status?: OrdersControllerFindAllAdminStatusEnum, search?: string, sortBy?: OrdersControllerFindAllAdminSortByEnum, sortOrder?: OrdersControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/orders/admin/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get detailed order information by order number. Validates ownership for customers.
         * @summary Get order by order number
         * @param {string} orderNumber Order number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindByOrderNumber: async (orderNumber: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderNumber' is not null or undefined
            assertParamExists('ordersControllerFindByOrderNumber', 'orderNumber', orderNumber)
            const localVarPath = `/api/v1/orders/number/{orderNumber}`
                .replace(`{${"orderNumber"}}`, encodeURIComponent(String(orderNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get detailed order information by ID. Validates ownership for customers, admins can view all.
         * @summary Get order by ID
         * @param {number} id Order ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ordersControllerFindOne', 'id', id)
            const localVarPath = `/api/v1/orders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get order statistics including total orders, revenue, status breakdown. Admin only.
         * @summary Get order statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerGetStatistics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/orders/admin/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update order status. Validates status transitions, creates history entry. Admin only.
         * @summary Update order status (Admin)
         * @param {number} id Order ID
         * @param {UpdateOrderStatusDto} updateOrderStatusDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerUpdateStatus: async (id: number, updateOrderStatusDto: UpdateOrderStatusDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('ordersControllerUpdateStatus', 'id', id)
            // verify required parameter 'updateOrderStatusDto' is not null or undefined
            assertParamExists('ordersControllerUpdateStatus', 'updateOrderStatusDto', updateOrderStatusDto)
            const localVarPath = `/api/v1/orders/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateOrderStatusDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrdersApi - functional programming interface
 * @export
 */
export const OrdersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrdersApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancel order. Only pending or confirmed orders can be cancelled by customer.
         * @summary Cancel order
         * @param {number} id Order ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerCancel(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerCancel(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerCancel']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Create a new order from current cart. Validates cart, addresses, stock. Clears cart after successful order.
         * @summary Create order from cart
         * @param {CreateOrderDto} createOrderDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerCreate(createOrderDto: CreateOrderDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerCreate(createOrderDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerCreate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get all orders for authenticated user with filters and pagination.
         * @summary Get all orders
         * @param {OrdersControllerFindAllStatusEnum} [status] Filter by order status
         * @param {string} [search] Search by order number, customer name, email
         * @param {OrdersControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {OrdersControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerFindAll(status?: OrdersControllerFindAllStatusEnum, search?: string, sortBy?: OrdersControllerFindAllSortByEnum, sortOrder?: OrdersControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerFindAll(status, search, sortBy, sortOrder, page, limit, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerFindAll']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get all orders from all users with filters and pagination. Admin only.
         * @summary Get all orders (Admin)
         * @param {OrdersControllerFindAllAdminStatusEnum} [status] Filter by order status
         * @param {string} [search] Search by order number, customer name, email
         * @param {OrdersControllerFindAllAdminSortByEnum} [sortBy] Sort by field
         * @param {OrdersControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerFindAllAdmin(status?: OrdersControllerFindAllAdminStatusEnum, search?: string, sortBy?: OrdersControllerFindAllAdminSortByEnum, sortOrder?: OrdersControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerFindAllAdmin(status, search, sortBy, sortOrder, page, limit, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerFindAllAdmin']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get detailed order information by order number. Validates ownership for customers.
         * @summary Get order by order number
         * @param {string} orderNumber Order number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerFindByOrderNumber(orderNumber: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerFindByOrderNumber(orderNumber, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerFindByOrderNumber']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get detailed order information by ID. Validates ownership for customers, admins can view all.
         * @summary Get order by ID
         * @param {number} id Order ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerFindOne(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerFindOne']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Get order statistics including total orders, revenue, status breakdown. Admin only.
         * @summary Get order statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerGetStatistics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerGetStatistics(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerGetStatistics']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Update order status. Validates status transitions, creates history entry. Admin only.
         * @summary Update order status (Admin)
         * @param {number} id Order ID
         * @param {UpdateOrderStatusDto} updateOrderStatusDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async ordersControllerUpdateStatus(id: number, updateOrderStatusDto: UpdateOrderStatusDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.ordersControllerUpdateStatus(id, updateOrderStatusDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['OrdersApi.ordersControllerUpdateStatus']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * OrdersApi - factory interface
 * @export
 */
export const OrdersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrdersApiFp(configuration)
    return {
        /**
         * Cancel order. Only pending or confirmed orders can be cancelled by customer.
         * @summary Cancel order
         * @param {number} id Order ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerCancel(id: number, options?: any): AxiosPromise<any> {
            return localVarFp.ordersControllerCancel(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new order from current cart. Validates cart, addresses, stock. Clears cart after successful order.
         * @summary Create order from cart
         * @param {CreateOrderDto} createOrderDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerCreate(createOrderDto: CreateOrderDto, options?: any): AxiosPromise<any> {
            return localVarFp.ordersControllerCreate(createOrderDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all orders for authenticated user with filters and pagination.
         * @summary Get all orders
         * @param {OrdersControllerFindAllStatusEnum} [status] Filter by order status
         * @param {string} [search] Search by order number, customer name, email
         * @param {OrdersControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {OrdersControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindAll(status?: OrdersControllerFindAllStatusEnum, search?: string, sortBy?: OrdersControllerFindAllSortByEnum, sortOrder?: OrdersControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: any): AxiosPromise<any> {
            return localVarFp.ordersControllerFindAll(status, search, sortBy, sortOrder, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all orders from all users with filters and pagination. Admin only.
         * @summary Get all orders (Admin)
         * @param {OrdersControllerFindAllAdminStatusEnum} [status] Filter by order status
         * @param {string} [search] Search by order number, customer name, email
         * @param {OrdersControllerFindAllAdminSortByEnum} [sortBy] Sort by field
         * @param {OrdersControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindAllAdmin(status?: OrdersControllerFindAllAdminStatusEnum, search?: string, sortBy?: OrdersControllerFindAllAdminSortByEnum, sortOrder?: OrdersControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: any): AxiosPromise<void> {
            return localVarFp.ordersControllerFindAllAdmin(status, search, sortBy, sortOrder, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get detailed order information by order number. Validates ownership for customers.
         * @summary Get order by order number
         * @param {string} orderNumber Order number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindByOrderNumber(orderNumber: string, options?: any): AxiosPromise<void> {
            return localVarFp.ordersControllerFindByOrderNumber(orderNumber, options).then((request) => request(axios, basePath));
        },
        /**
         * Get detailed order information by ID. Validates ownership for customers, admins can view all.
         * @summary Get order by ID
         * @param {number} id Order ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerFindOne(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.ordersControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get order statistics including total orders, revenue, status breakdown. Admin only.
         * @summary Get order statistics (Admin)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerGetStatistics(options?: any): AxiosPromise<any> {
            return localVarFp.ordersControllerGetStatistics(options).then((request) => request(axios, basePath));
        },
        /**
         * Update order status. Validates status transitions, creates history entry. Admin only.
         * @summary Update order status (Admin)
         * @param {number} id Order ID
         * @param {UpdateOrderStatusDto} updateOrderStatusDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        ordersControllerUpdateStatus(id: number, updateOrderStatusDto: UpdateOrderStatusDto, options?: any): AxiosPromise<void> {
            return localVarFp.ordersControllerUpdateStatus(id, updateOrderStatusDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrdersApi - interface
 * @export
 * @interface OrdersApi
 */
export interface OrdersApiInterface {
    /**
     * Cancel order. Only pending or confirmed orders can be cancelled by customer.
     * @summary Cancel order
     * @param {number} id Order ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerCancel(id: number, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Create a new order from current cart. Validates cart, addresses, stock. Clears cart after successful order.
     * @summary Create order from cart
     * @param {CreateOrderDto} createOrderDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerCreate(createOrderDto: CreateOrderDto, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Get all orders for authenticated user with filters and pagination.
     * @summary Get all orders
     * @param {OrdersControllerFindAllStatusEnum} [status] Filter by order status
     * @param {string} [search] Search by order number, customer name, email
     * @param {OrdersControllerFindAllSortByEnum} [sortBy] Sort by field
     * @param {OrdersControllerFindAllSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerFindAll(status?: OrdersControllerFindAllStatusEnum, search?: string, sortBy?: OrdersControllerFindAllSortByEnum, sortOrder?: OrdersControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Get all orders from all users with filters and pagination. Admin only.
     * @summary Get all orders (Admin)
     * @param {OrdersControllerFindAllAdminStatusEnum} [status] Filter by order status
     * @param {string} [search] Search by order number, customer name, email
     * @param {OrdersControllerFindAllAdminSortByEnum} [sortBy] Sort by field
     * @param {OrdersControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerFindAllAdmin(status?: OrdersControllerFindAllAdminStatusEnum, search?: string, sortBy?: OrdersControllerFindAllAdminSortByEnum, sortOrder?: OrdersControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get detailed order information by order number. Validates ownership for customers.
     * @summary Get order by order number
     * @param {string} orderNumber Order number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerFindByOrderNumber(orderNumber: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get detailed order information by ID. Validates ownership for customers, admins can view all.
     * @summary Get order by ID
     * @param {number} id Order ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get order statistics including total orders, revenue, status breakdown. Admin only.
     * @summary Get order statistics (Admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerGetStatistics(options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Update order status. Validates status transitions, creates history entry. Admin only.
     * @summary Update order status (Admin)
     * @param {number} id Order ID
     * @param {UpdateOrderStatusDto} updateOrderStatusDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    ordersControllerUpdateStatus(id: number, updateOrderStatusDto: UpdateOrderStatusDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * OrdersApi - object-oriented interface
 * @export
 * @class OrdersApi
 * @extends {BaseAPI}
 */
export class OrdersApi extends BaseAPI implements OrdersApiInterface {
    /**
     * Cancel order. Only pending or confirmed orders can be cancelled by customer.
     * @summary Cancel order
     * @param {number} id Order ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerCancel(id: number, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerCancel(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new order from current cart. Validates cart, addresses, stock. Clears cart after successful order.
     * @summary Create order from cart
     * @param {CreateOrderDto} createOrderDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerCreate(createOrderDto: CreateOrderDto, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerCreate(createOrderDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all orders for authenticated user with filters and pagination.
     * @summary Get all orders
     * @param {OrdersControllerFindAllStatusEnum} [status] Filter by order status
     * @param {string} [search] Search by order number, customer name, email
     * @param {OrdersControllerFindAllSortByEnum} [sortBy] Sort by field
     * @param {OrdersControllerFindAllSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerFindAll(status?: OrdersControllerFindAllStatusEnum, search?: string, sortBy?: OrdersControllerFindAllSortByEnum, sortOrder?: OrdersControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerFindAll(status, search, sortBy, sortOrder, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all orders from all users with filters and pagination. Admin only.
     * @summary Get all orders (Admin)
     * @param {OrdersControllerFindAllAdminStatusEnum} [status] Filter by order status
     * @param {string} [search] Search by order number, customer name, email
     * @param {OrdersControllerFindAllAdminSortByEnum} [sortBy] Sort by field
     * @param {OrdersControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerFindAllAdmin(status?: OrdersControllerFindAllAdminStatusEnum, search?: string, sortBy?: OrdersControllerFindAllAdminSortByEnum, sortOrder?: OrdersControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerFindAllAdmin(status, search, sortBy, sortOrder, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get detailed order information by order number. Validates ownership for customers.
     * @summary Get order by order number
     * @param {string} orderNumber Order number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerFindByOrderNumber(orderNumber: string, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerFindByOrderNumber(orderNumber, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get detailed order information by ID. Validates ownership for customers, admins can view all.
     * @summary Get order by ID
     * @param {number} id Order ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get order statistics including total orders, revenue, status breakdown. Admin only.
     * @summary Get order statistics (Admin)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerGetStatistics(options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerGetStatistics(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update order status. Validates status transitions, creates history entry. Admin only.
     * @summary Update order status (Admin)
     * @param {number} id Order ID
     * @param {UpdateOrderStatusDto} updateOrderStatusDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApi
     */
    public ordersControllerUpdateStatus(id: number, updateOrderStatusDto: UpdateOrderStatusDto, options?: RawAxiosRequestConfig) {
        return OrdersApiFp(this.configuration).ordersControllerUpdateStatus(id, updateOrderStatusDto, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const OrdersControllerFindAllStatusEnum = {
    ALL: 'all',
    _1: '1',
    _2: '2',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7'
} as const;
export type OrdersControllerFindAllStatusEnum = typeof OrdersControllerFindAllStatusEnum[keyof typeof OrdersControllerFindAllStatusEnum];
/**
 * @export
 */
export const OrdersControllerFindAllSortByEnum = {
    CREATED_AT: 'created_at',
    TOTAL_AMOUNT: 'total_amount',
    ORDER_NUMBER: 'order_number'
} as const;
export type OrdersControllerFindAllSortByEnum = typeof OrdersControllerFindAllSortByEnum[keyof typeof OrdersControllerFindAllSortByEnum];
/**
 * @export
 */
export const OrdersControllerFindAllSortOrderEnum = {
    ASC: 'asc',
    DESC: 'desc'
} as const;
export type OrdersControllerFindAllSortOrderEnum = typeof OrdersControllerFindAllSortOrderEnum[keyof typeof OrdersControllerFindAllSortOrderEnum];
/**
 * @export
 */
export const OrdersControllerFindAllAdminStatusEnum = {
    ALL: 'all',
    _1: '1',
    _2: '2',
    _3: '3',
    _4: '4',
    _5: '5',
    _6: '6',
    _7: '7'
} as const;
export type OrdersControllerFindAllAdminStatusEnum = typeof OrdersControllerFindAllAdminStatusEnum[keyof typeof OrdersControllerFindAllAdminStatusEnum];
/**
 * @export
 */
export const OrdersControllerFindAllAdminSortByEnum = {
    CREATED_AT: 'created_at',
    TOTAL_AMOUNT: 'total_amount',
    ORDER_NUMBER: 'order_number'
} as const;
export type OrdersControllerFindAllAdminSortByEnum = typeof OrdersControllerFindAllAdminSortByEnum[keyof typeof OrdersControllerFindAllAdminSortByEnum];
/**
 * @export
 */
export const OrdersControllerFindAllAdminSortOrderEnum = {
    ASC: 'asc',
    DESC: 'desc'
} as const;
export type OrdersControllerFindAllAdminSortOrderEnum = typeof OrdersControllerFindAllAdminSortOrderEnum[keyof typeof OrdersControllerFindAllAdminSortOrderEnum];
