/* tslint:disable */
/* eslint-disable */
/**
 * NetworkStore API
 * E-commerce API for network equipment store
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { AdminReplyDto } from '../models';
// @ts-ignore
import { CreateReviewDto } from '../models';
// @ts-ignore
import { UpdateReviewDto } from '../models';
/**
 * ReviewsApi - axios parameter creator
 * @export
 */
export const ReviewsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add admin reply to review
         * @param {string} id Review ID
         * @param {AdminReplyDto} adminReplyDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerAddReply: async (id: string, adminReplyDto: AdminReplyDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewsControllerAddReply', 'id', id)
            // verify required parameter 'adminReplyDto' is not null or undefined
            assertParamExists('reviewsControllerAddReply', 'adminReplyDto', adminReplyDto)
            const localVarPath = `/api/v1/reviews/{id}/reply`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(adminReplyDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Approve review (admin only)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerApprove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewsControllerApprove', 'id', id)
            const localVarPath = `/api/v1/reviews/{id}/approve`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new review
         * @param {CreateReviewDto} createReviewDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerCreate: async (createReviewDto: CreateReviewDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createReviewDto' is not null or undefined
            assertParamExists('reviewsControllerCreate', 'createReviewDto', createReviewDto)
            const localVarPath = `/api/v1/reviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReviewDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all reviews with filters
         * @param {number} [productId] Filter by product ID
         * @param {number} [userId] Filter by user ID
         * @param {ReviewsControllerFindAllRatingEnum} [rating] Filter by rating (1-5)
         * @param {ReviewsControllerFindAllStatusEnum} [status] Filter by approval status
         * @param {ReviewsControllerFindAllVerifiedEnum} [verified] Filter by verified purchase
         * @param {string} [search] Search in title and comment
         * @param {ReviewsControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {ReviewsControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerFindAll: async (productId?: number, userId?: number, rating?: ReviewsControllerFindAllRatingEnum, status?: ReviewsControllerFindAllStatusEnum, verified?: ReviewsControllerFindAllVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllSortByEnum, sortOrder?: ReviewsControllerFindAllSortOrderEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/reviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (productId !== undefined) {
                localVarQueryParameter['product_id'] = productId;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (rating !== undefined) {
                localVarQueryParameter['rating'] = rating;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (verified !== undefined) {
                localVarQueryParameter['verified'] = verified;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all reviews (Admin - including pending)
         * @param {number} [productId] Filter by product ID
         * @param {number} [userId] Filter by user ID
         * @param {ReviewsControllerFindAllAdminRatingEnum} [rating] Filter by rating (1-5)
         * @param {ReviewsControllerFindAllAdminStatusEnum} [status] Filter by approval status
         * @param {ReviewsControllerFindAllAdminVerifiedEnum} [verified] Filter by verified purchase
         * @param {string} [search] Search in title and comment
         * @param {ReviewsControllerFindAllAdminSortByEnum} [sortBy] Sort by field
         * @param {ReviewsControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerFindAllAdmin: async (productId?: number, userId?: number, rating?: ReviewsControllerFindAllAdminRatingEnum, status?: ReviewsControllerFindAllAdminStatusEnum, verified?: ReviewsControllerFindAllAdminVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllAdminSortByEnum, sortOrder?: ReviewsControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/reviews/admin/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (productId !== undefined) {
                localVarQueryParameter['product_id'] = productId;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (rating !== undefined) {
                localVarQueryParameter['rating'] = rating;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (verified !== undefined) {
                localVarQueryParameter['verified'] = verified;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get review by ID
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewsControllerFindOne', 'id', id)
            const localVarPath = `/api/v1/reviews/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get product rating statistics
         * @param {string} productId Product ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerGetProductStats: async (productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('reviewsControllerGetProductStats', 'productId', productId)
            const localVarPath = `/api/v1/reviews/products/{productId}/stats`
                .replace(`{${"productId"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Mark review as helpful
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerMarkHelpful: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewsControllerMarkHelpful', 'id', id)
            const localVarPath = `/api/v1/reviews/{id}/helpful`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject review (admin only)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerReject: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewsControllerReject', 'id', id)
            const localVarPath = `/api/v1/reviews/{id}/reject`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete review (owner or admin)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewsControllerRemove', 'id', id)
            const localVarPath = `/api/v1/reviews/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update review (owner only)
         * @param {string} id Review ID
         * @param {UpdateReviewDto} updateReviewDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerUpdate: async (id: string, updateReviewDto: UpdateReviewDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewsControllerUpdate', 'id', id)
            // verify required parameter 'updateReviewDto' is not null or undefined
            assertParamExists('reviewsControllerUpdate', 'updateReviewDto', updateReviewDto)
            const localVarPath = `/api/v1/reviews/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateReviewDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReviewsApi - functional programming interface
 * @export
 */
export const ReviewsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReviewsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add admin reply to review
         * @param {string} id Review ID
         * @param {AdminReplyDto} adminReplyDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerAddReply(id: string, adminReplyDto: AdminReplyDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerAddReply(id, adminReplyDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerAddReply']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Approve review (admin only)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerApprove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerApprove(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerApprove']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new review
         * @param {CreateReviewDto} createReviewDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerCreate(createReviewDto: CreateReviewDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerCreate(createReviewDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerCreate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get all reviews with filters
         * @param {number} [productId] Filter by product ID
         * @param {number} [userId] Filter by user ID
         * @param {ReviewsControllerFindAllRatingEnum} [rating] Filter by rating (1-5)
         * @param {ReviewsControllerFindAllStatusEnum} [status] Filter by approval status
         * @param {ReviewsControllerFindAllVerifiedEnum} [verified] Filter by verified purchase
         * @param {string} [search] Search in title and comment
         * @param {ReviewsControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {ReviewsControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerFindAll(productId?: number, userId?: number, rating?: ReviewsControllerFindAllRatingEnum, status?: ReviewsControllerFindAllStatusEnum, verified?: ReviewsControllerFindAllVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllSortByEnum, sortOrder?: ReviewsControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerFindAll(productId, userId, rating, status, verified, search, sortBy, sortOrder, page, limit, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerFindAll']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get all reviews (Admin - including pending)
         * @param {number} [productId] Filter by product ID
         * @param {number} [userId] Filter by user ID
         * @param {ReviewsControllerFindAllAdminRatingEnum} [rating] Filter by rating (1-5)
         * @param {ReviewsControllerFindAllAdminStatusEnum} [status] Filter by approval status
         * @param {ReviewsControllerFindAllAdminVerifiedEnum} [verified] Filter by verified purchase
         * @param {string} [search] Search in title and comment
         * @param {ReviewsControllerFindAllAdminSortByEnum} [sortBy] Sort by field
         * @param {ReviewsControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerFindAllAdmin(productId?: number, userId?: number, rating?: ReviewsControllerFindAllAdminRatingEnum, status?: ReviewsControllerFindAllAdminStatusEnum, verified?: ReviewsControllerFindAllAdminVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllAdminSortByEnum, sortOrder?: ReviewsControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerFindAllAdmin(productId, userId, rating, status, verified, search, sortBy, sortOrder, page, limit, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerFindAllAdmin']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get review by ID
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerFindOne(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerFindOne']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Get product rating statistics
         * @param {string} productId Product ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerGetProductStats(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerGetProductStats(productId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerGetProductStats']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Mark review as helpful
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerMarkHelpful(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerMarkHelpful(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerMarkHelpful']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Reject review (admin only)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerReject(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerReject(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerReject']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Delete review (owner or admin)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerRemove(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerRemove']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Update review (owner only)
         * @param {string} id Review ID
         * @param {UpdateReviewDto} updateReviewDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewsControllerUpdate(id: string, updateReviewDto: UpdateReviewDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewsControllerUpdate(id, updateReviewDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['ReviewsApi.reviewsControllerUpdate']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * ReviewsApi - factory interface
 * @export
 */
export const ReviewsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReviewsApiFp(configuration)
    return {
        /**
         * 
         * @summary Add admin reply to review
         * @param {string} id Review ID
         * @param {AdminReplyDto} adminReplyDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerAddReply(id: string, adminReplyDto: AdminReplyDto, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerAddReply(id, adminReplyDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Approve review (admin only)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerApprove(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerApprove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new review
         * @param {CreateReviewDto} createReviewDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerCreate(createReviewDto: CreateReviewDto, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerCreate(createReviewDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all reviews with filters
         * @param {number} [productId] Filter by product ID
         * @param {number} [userId] Filter by user ID
         * @param {ReviewsControllerFindAllRatingEnum} [rating] Filter by rating (1-5)
         * @param {ReviewsControllerFindAllStatusEnum} [status] Filter by approval status
         * @param {ReviewsControllerFindAllVerifiedEnum} [verified] Filter by verified purchase
         * @param {string} [search] Search in title and comment
         * @param {ReviewsControllerFindAllSortByEnum} [sortBy] Sort by field
         * @param {ReviewsControllerFindAllSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerFindAll(productId?: number, userId?: number, rating?: ReviewsControllerFindAllRatingEnum, status?: ReviewsControllerFindAllStatusEnum, verified?: ReviewsControllerFindAllVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllSortByEnum, sortOrder?: ReviewsControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerFindAll(productId, userId, rating, status, verified, search, sortBy, sortOrder, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all reviews (Admin - including pending)
         * @param {number} [productId] Filter by product ID
         * @param {number} [userId] Filter by user ID
         * @param {ReviewsControllerFindAllAdminRatingEnum} [rating] Filter by rating (1-5)
         * @param {ReviewsControllerFindAllAdminStatusEnum} [status] Filter by approval status
         * @param {ReviewsControllerFindAllAdminVerifiedEnum} [verified] Filter by verified purchase
         * @param {string} [search] Search in title and comment
         * @param {ReviewsControllerFindAllAdminSortByEnum} [sortBy] Sort by field
         * @param {ReviewsControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
         * @param {number} [page] Page number
         * @param {number} [limit] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerFindAllAdmin(productId?: number, userId?: number, rating?: ReviewsControllerFindAllAdminRatingEnum, status?: ReviewsControllerFindAllAdminStatusEnum, verified?: ReviewsControllerFindAllAdminVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllAdminSortByEnum, sortOrder?: ReviewsControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerFindAllAdmin(productId, userId, rating, status, verified, search, sortBy, sortOrder, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get review by ID
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerFindOne(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get product rating statistics
         * @param {string} productId Product ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerGetProductStats(productId: string, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerGetProductStats(productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Mark review as helpful
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerMarkHelpful(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerMarkHelpful(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject review (admin only)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerReject(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerReject(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete review (owner or admin)
         * @param {string} id Review ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerRemove(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update review (owner only)
         * @param {string} id Review ID
         * @param {UpdateReviewDto} updateReviewDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewsControllerUpdate(id: string, updateReviewDto: UpdateReviewDto, options?: any): AxiosPromise<void> {
            return localVarFp.reviewsControllerUpdate(id, updateReviewDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReviewsApi - interface
 * @export
 * @interface ReviewsApi
 */
export interface ReviewsApiInterface {
    /**
     * 
     * @summary Add admin reply to review
     * @param {string} id Review ID
     * @param {AdminReplyDto} adminReplyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerAddReply(id: string, adminReplyDto: AdminReplyDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Approve review (admin only)
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerApprove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Create a new review
     * @param {CreateReviewDto} createReviewDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerCreate(createReviewDto: CreateReviewDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all reviews with filters
     * @param {number} [productId] Filter by product ID
     * @param {number} [userId] Filter by user ID
     * @param {ReviewsControllerFindAllRatingEnum} [rating] Filter by rating (1-5)
     * @param {ReviewsControllerFindAllStatusEnum} [status] Filter by approval status
     * @param {ReviewsControllerFindAllVerifiedEnum} [verified] Filter by verified purchase
     * @param {string} [search] Search in title and comment
     * @param {ReviewsControllerFindAllSortByEnum} [sortBy] Sort by field
     * @param {ReviewsControllerFindAllSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerFindAll(productId?: number, userId?: number, rating?: ReviewsControllerFindAllRatingEnum, status?: ReviewsControllerFindAllStatusEnum, verified?: ReviewsControllerFindAllVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllSortByEnum, sortOrder?: ReviewsControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all reviews (Admin - including pending)
     * @param {number} [productId] Filter by product ID
     * @param {number} [userId] Filter by user ID
     * @param {ReviewsControllerFindAllAdminRatingEnum} [rating] Filter by rating (1-5)
     * @param {ReviewsControllerFindAllAdminStatusEnum} [status] Filter by approval status
     * @param {ReviewsControllerFindAllAdminVerifiedEnum} [verified] Filter by verified purchase
     * @param {string} [search] Search in title and comment
     * @param {ReviewsControllerFindAllAdminSortByEnum} [sortBy] Sort by field
     * @param {ReviewsControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerFindAllAdmin(productId?: number, userId?: number, rating?: ReviewsControllerFindAllAdminRatingEnum, status?: ReviewsControllerFindAllAdminStatusEnum, verified?: ReviewsControllerFindAllAdminVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllAdminSortByEnum, sortOrder?: ReviewsControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get review by ID
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get product rating statistics
     * @param {string} productId Product ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerGetProductStats(productId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Mark review as helpful
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerMarkHelpful(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Reject review (admin only)
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerReject(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Delete review (owner or admin)
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Update review (owner only)
     * @param {string} id Review ID
     * @param {UpdateReviewDto} updateReviewDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewsControllerUpdate(id: string, updateReviewDto: UpdateReviewDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * ReviewsApi - object-oriented interface
 * @export
 * @class ReviewsApi
 * @extends {BaseAPI}
 */
export class ReviewsApi extends BaseAPI implements ReviewsApiInterface {
    /**
     * 
     * @summary Add admin reply to review
     * @param {string} id Review ID
     * @param {AdminReplyDto} adminReplyDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerAddReply(id: string, adminReplyDto: AdminReplyDto, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerAddReply(id, adminReplyDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Approve review (admin only)
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerApprove(id: string, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerApprove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new review
     * @param {CreateReviewDto} createReviewDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerCreate(createReviewDto: CreateReviewDto, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerCreate(createReviewDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all reviews with filters
     * @param {number} [productId] Filter by product ID
     * @param {number} [userId] Filter by user ID
     * @param {ReviewsControllerFindAllRatingEnum} [rating] Filter by rating (1-5)
     * @param {ReviewsControllerFindAllStatusEnum} [status] Filter by approval status
     * @param {ReviewsControllerFindAllVerifiedEnum} [verified] Filter by verified purchase
     * @param {string} [search] Search in title and comment
     * @param {ReviewsControllerFindAllSortByEnum} [sortBy] Sort by field
     * @param {ReviewsControllerFindAllSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerFindAll(productId?: number, userId?: number, rating?: ReviewsControllerFindAllRatingEnum, status?: ReviewsControllerFindAllStatusEnum, verified?: ReviewsControllerFindAllVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllSortByEnum, sortOrder?: ReviewsControllerFindAllSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerFindAll(productId, userId, rating, status, verified, search, sortBy, sortOrder, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all reviews (Admin - including pending)
     * @param {number} [productId] Filter by product ID
     * @param {number} [userId] Filter by user ID
     * @param {ReviewsControllerFindAllAdminRatingEnum} [rating] Filter by rating (1-5)
     * @param {ReviewsControllerFindAllAdminStatusEnum} [status] Filter by approval status
     * @param {ReviewsControllerFindAllAdminVerifiedEnum} [verified] Filter by verified purchase
     * @param {string} [search] Search in title and comment
     * @param {ReviewsControllerFindAllAdminSortByEnum} [sortBy] Sort by field
     * @param {ReviewsControllerFindAllAdminSortOrderEnum} [sortOrder] Sort order
     * @param {number} [page] Page number
     * @param {number} [limit] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerFindAllAdmin(productId?: number, userId?: number, rating?: ReviewsControllerFindAllAdminRatingEnum, status?: ReviewsControllerFindAllAdminStatusEnum, verified?: ReviewsControllerFindAllAdminVerifiedEnum, search?: string, sortBy?: ReviewsControllerFindAllAdminSortByEnum, sortOrder?: ReviewsControllerFindAllAdminSortOrderEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerFindAllAdmin(productId, userId, rating, status, verified, search, sortBy, sortOrder, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get review by ID
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get product rating statistics
     * @param {string} productId Product ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerGetProductStats(productId: string, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerGetProductStats(productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Mark review as helpful
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerMarkHelpful(id: string, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerMarkHelpful(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject review (admin only)
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerReject(id: string, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerReject(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete review (owner or admin)
     * @param {string} id Review ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update review (owner only)
     * @param {string} id Review ID
     * @param {UpdateReviewDto} updateReviewDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApi
     */
    public reviewsControllerUpdate(id: string, updateReviewDto: UpdateReviewDto, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reviewsControllerUpdate(id, updateReviewDto, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ReviewsControllerFindAllRatingEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type ReviewsControllerFindAllRatingEnum = typeof ReviewsControllerFindAllRatingEnum[keyof typeof ReviewsControllerFindAllRatingEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllStatusEnum = {
    ALL: 'all',
    APPROVED: 'approved',
    PENDING: 'pending',
    REJECTED: 'rejected'
} as const;
export type ReviewsControllerFindAllStatusEnum = typeof ReviewsControllerFindAllStatusEnum[keyof typeof ReviewsControllerFindAllStatusEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllVerifiedEnum = {
    ALL: 'all',
    TRUE: 'true',
    FALSE: 'false'
} as const;
export type ReviewsControllerFindAllVerifiedEnum = typeof ReviewsControllerFindAllVerifiedEnum[keyof typeof ReviewsControllerFindAllVerifiedEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllSortByEnum = {
    CREATED_AT: 'created_at',
    RATING: 'rating',
    HELPFUL_COUNT: 'helpful_count'
} as const;
export type ReviewsControllerFindAllSortByEnum = typeof ReviewsControllerFindAllSortByEnum[keyof typeof ReviewsControllerFindAllSortByEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllSortOrderEnum = {
    ASC: 'asc',
    DESC: 'desc'
} as const;
export type ReviewsControllerFindAllSortOrderEnum = typeof ReviewsControllerFindAllSortOrderEnum[keyof typeof ReviewsControllerFindAllSortOrderEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllAdminRatingEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type ReviewsControllerFindAllAdminRatingEnum = typeof ReviewsControllerFindAllAdminRatingEnum[keyof typeof ReviewsControllerFindAllAdminRatingEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllAdminStatusEnum = {
    ALL: 'all',
    APPROVED: 'approved',
    PENDING: 'pending',
    REJECTED: 'rejected'
} as const;
export type ReviewsControllerFindAllAdminStatusEnum = typeof ReviewsControllerFindAllAdminStatusEnum[keyof typeof ReviewsControllerFindAllAdminStatusEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllAdminVerifiedEnum = {
    ALL: 'all',
    TRUE: 'true',
    FALSE: 'false'
} as const;
export type ReviewsControllerFindAllAdminVerifiedEnum = typeof ReviewsControllerFindAllAdminVerifiedEnum[keyof typeof ReviewsControllerFindAllAdminVerifiedEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllAdminSortByEnum = {
    CREATED_AT: 'created_at',
    RATING: 'rating',
    HELPFUL_COUNT: 'helpful_count'
} as const;
export type ReviewsControllerFindAllAdminSortByEnum = typeof ReviewsControllerFindAllAdminSortByEnum[keyof typeof ReviewsControllerFindAllAdminSortByEnum];
/**
 * @export
 */
export const ReviewsControllerFindAllAdminSortOrderEnum = {
    ASC: 'asc',
    DESC: 'desc'
} as const;
export type ReviewsControllerFindAllAdminSortOrderEnum = typeof ReviewsControllerFindAllAdminSortOrderEnum[keyof typeof ReviewsControllerFindAllAdminSortOrderEnum];
